trigger:
  branches:
   include:
     - main
  paths:
    include:
    - /My_practices/variables/main-varaible.yaml

pool:
  vmImage: ubuntu-latest

stages:
- stage: stg1
  jobs:
  - job: job1
    continueOnError: true
    displayName: job1
    variables:
    - template: /My_practices/variables/variables-template.yaml
    steps:
    - script: echo $(Gvar1) ${{ variables.var_1 }} ${{ variables.var_2 }} 