parameters: 
- name: loop_values
  type: object
  default: []

jobs:
- jobs: job1
  displayname: job1
  continueOnError: true
  workspace:
    clean: outputs
  steps:
  - ${{ each value in parameters.loop_values}}:
    - script: echo ${{ value }}
      displayName: step 1
  - script: echo step 2
    displayName: step 2
